// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aeaeukuvnyezklenpybi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlYWV1a3V2bnllemtsZW5weWJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNTU4NjAsImV4cCI6MjA3MDYzMTg2MH0.n49ca5cfm9VXKl4YPJRwjqe7KYLoWkITKO87qNMcxp0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});